---
name: Sample
description: "Rule which sends an email when an email from johndoe@gmail.com is received"
pack: email
enabled: true
trigger:
  type: email.imap.message
  parameters: {}
criteria:
  trigger.subject:
    pattern: vm_create
    type: contains
action:
  ref: create_vm.create_instance
  parameters:
    ImageId: 'ami-0d2692b6acea72ee6'
    InstanceType: 't2.micro'
    KeyName: 'ec2-keypair'
    
